services:
  backend:
    build: ./backend
    container_name: dashboard-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app/db/db.sqlite3:/app/app/db/db.sqlite3
    networks:
      - dashboard-net

  frontend:
    build: ./frontend
    container_name: dashboard-frontend
    ports:
      - "5173:5173"
    networks:
      - dashboard-net
    depends_on:
      - backend

  nginx:
    image: nginx:1.25
    container_name: dashboard-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend
    networks:
      - dashboard-net

networks:
  dashboard-net:
    driver: bridge
