/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload Health */
        post: operations["upload_health_api_health__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health/weight": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Weight History */
        get: operations["weight_history_api_health_weight_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health/maintenance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Maintenance Calories */
        get: operations["maintenance_calories_api_health_maintenance_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health/macros": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Macros History */
        get: operations["macros_history_api_health_macros_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health/workouts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Workout History */
        get: operations["workout_history_api_health_workouts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/investments/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Financial Data */
        get: operations["get_financial_data_api_investments__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/investments/monte-carlo-simulations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start Monte Carlo Simulation */
        post: operations["start_monte_carlo_simulation_api_investments_monte_carlo_simulations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/investments/monte-carlo-simulations/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Monte Carlo Simulation Result */
        get: operations["get_monte_carlo_simulation_result_api_investments_monte_carlo_simulations__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AccountInfo */
        AccountInfo: {
            /** Currency */
            currency: string;
            /** Type */
            type: string;
            /** Id */
            id: string;
        };
        /** Body_upload_health_api_health__post */
        Body_upload_health_api_health__post: {
            /**
             * File
             * Format: binary
             */
            file: string;
        };
        /** CashReport */
        CashReport: {
            /** Starting */
            starting: number;
            /** Ending */
            ending: number;
            /** Deposits */
            deposits: number;
            /** Withdrawals */
            withdrawals: number;
        };
        /** CashTransaction */
        CashTransaction: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Amount */
            amount: number;
            /** Type */
            type: string;
            /** Fxratetobase */
            fxRateToBase: number;
        };
        /** DailyNutrient */
        DailyNutrient: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Value */
            value: number;
            /** Ma7 */
            ma7?: number | null;
            /** Ma30 */
            ma30?: number | null;
            /** Ma90 */
            ma90?: number | null;
        };
        /** FinancialReport */
        FinancialReport: {
            /** Reports */
            reports: number;
            /**
             * Fromdate
             * Format: date
             */
            fromDate: string;
            /**
             * Todate
             * Format: date
             */
            toDate: string;
            account: components["schemas"]["AccountInfo"];
            cashReport: components["schemas"]["CashReport"];
            /** Valueovertime */
            valueOverTime: components["schemas"]["ValueOverTimePoint"][];
            /** Statementfunds */
            statementFunds: components["schemas"]["StatementFund"][];
            /** Openpositions */
            openPositions: components["schemas"]["OpenPosition"][];
            /** Trades */
            trades: components["schemas"]["Trade"][];
            /** Cashtransactions */
            cashTransactions: components["schemas"]["CashTransaction"][];
            timeWeightedReturn: components["schemas"]["TimeWeightedReturn"];
        };
        /** GoalAchievement */
        GoalAchievement: {
            /** Targetvalue */
            targetValue: number;
            /** Successprobability */
            successProbability: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** MaintenanceEstimate */
        MaintenanceEstimate: {
            /** Estimated Maintenance Calories */
            estimated_maintenance_calories: number;
            /** Kg Per Day */
            kg_per_day: number;
            /** Kg Per Week */
            kg_per_week: number;
            /** Kg Per Month */
            kg_per_month: number;
            /** Avg Daily Calories */
            avg_daily_calories: number;
            /** Pred Start Weight */
            pred_start_weight: number;
            /** Pred End Weight */
            pred_end_weight: number;
            /** Total Weight Change */
            total_weight_change: number;
            /** Days Used */
            days_used: number;
        };
        /** MonteCarloRequest */
        MonteCarloRequest: {
            /** Start Value */
            start_value: number;
            /** Twr Series */
            twr_series: {
                [key: string]: unknown;
            }[];
            /**
             * Monthly Deposit
             * @default 200
             */
            monthly_deposit: number;
            /**
             * Monthly Withdrawal
             * @default 0
             */
            monthly_withdrawal: number;
            /**
             * Days Ahead
             * @default 100
             */
            days_ahead: number;
            /**
             * Sims
             * @default 5000
             */
            sims: number;
            /** Target Value */
            target_value?: number | null;
        };
        /** MonteCarloResponse */
        MonteCarloResponse: {
            /**
             * Job Id
             * Format: uuid
             */
            job_id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "running" | "finished";
            result?: components["schemas"]["MonteCarloResult"] | null;
        };
        /** MonteCarloResult */
        MonteCarloResult: {
            /** Portfolioprojection */
            portfolioProjection: components["schemas"]["PortfolioProjectionPoint"][];
            goalAchievement: components["schemas"]["GoalAchievement"] | null;
        };
        /** NutrientStats */
        NutrientStats: {
            /** Daily */
            daily: components["schemas"]["DailyNutrient"][];
            /** Summary */
            summary: {
                [key: string]: number;
            };
        };
        /** OpenPosition */
        OpenPosition: {
            /** Currency */
            currency: string;
            /** Symbol */
            symbol: string;
            /** Description */
            description: string;
            /** Position */
            position: number;
            /** Markprice */
            markPrice: number;
            /** Positionvalue */
            positionValue: number;
            /** Costbasisprice */
            costBasisPrice: number;
            /** Costbasismoney */
            costBasisMoney: number;
            /** Percentofnav */
            percentOfNAV: number;
            /** Fxratetobase */
            fxRateToBase: number;
        };
        /** PortfolioProjectionPoint */
        PortfolioProjectionPoint: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** P5 */
            p5: number;
            /** P25 */
            p25: number;
            /** P50 */
            p50: number;
            /** P75 */
            p75: number;
            /** P95 */
            p95: number;
            /** Baseline */
            baseline: number;
        };
        /** StatementFund */
        StatementFund: {
            /** Amount */
            amount: number;
            /** Symbol */
            symbol: string;
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Activitycode */
            activityCode: string;
            /** Activitydescription */
            activityDescription: string;
        };
        /** TimeWeightedReturn */
        TimeWeightedReturn: {
            /** Total */
            total: number;
            /** Series */
            series: components["schemas"]["TimeWeightedReturnItem"][];
        };
        /** TimeWeightedReturnItem */
        TimeWeightedReturnItem: {
            /** Date */
            date: string;
            /** Twr */
            twr: number;
        };
        /** Trade */
        Trade: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Quantity */
            quantity: number;
            /** Tradeprice */
            tradePrice: number;
            /** Ibcommission */
            ibCommission: number;
            /** Buysell */
            buySell: string;
            /** Netcash */
            netCash: number;
            /** Symbol */
            symbol: string;
        };
        /** UploadResponse */
        UploadResponse: {
            /** Imported */
            imported: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** ValueOverTimePoint */
        ValueOverTimePoint: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Cash */
            cash: number;
            /** Total */
            total: number;
        };
        /** WeightResponse */
        WeightResponse: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Value */
            value: number;
            /** Ma7 */
            ma7?: number | null;
            /** Ma30 */
            ma30?: number | null;
            /** Ma90 */
            ma90?: number | null;
        };
        /** WorkoutDaily */
        WorkoutDaily: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Duration */
            duration: number;
        };
        /** WorkoutStats */
        WorkoutStats: {
            /** Daily Stats */
            daily_stats: components["schemas"]["WorkoutDaily"][];
            /** Total Sessions */
            total_sessions: number;
            /** Total Duration Min */
            total_duration_min: number;
            /** Avg Session Duration Min */
            avg_session_duration_min: number;
            /** Longest Session Min */
            longest_session_min: number;
            /** Sessions Per Weekday */
            sessions_per_weekday: {
                [key: string]: number;
            };
            /** Sessions Per Week */
            sessions_per_week: {
                [key: string]: number;
            };
            /** Sessions Per Month */
            sessions_per_month: {
                [key: string]: number;
            };
            /** Longest Streak Days */
            longest_streak_days: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    upload_health_api_health__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_health_api_health__post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    weight_history_api_health_weight_get: {
        parameters: {
            query?: {
                start_date?: string | null;
                end_date?: string | null;
                ma_windows?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WeightResponse"][] | null;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    maintenance_calories_api_health_maintenance_get: {
        parameters: {
            query?: {
                start_date?: string | null;
                end_date?: string | null;
                min_daily_calories?: number | null;
                calories_ma_window?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MaintenanceEstimate"] | null;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    macros_history_api_health_macros_get: {
        parameters: {
            query?: {
                start_date?: string | null;
                end_date?: string | null;
                ma_windows?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: components["schemas"]["NutrientStats"];
                    } | null;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    workout_history_api_health_workouts_get: {
        parameters: {
            query?: {
                start_date?: string | null;
                end_date?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkoutStats"] | null;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_financial_data_api_investments__get: {
        parameters: {
            query?: {
                start_date?: string | null;
                end_date?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FinancialReport"] | null;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_monte_carlo_simulation_api_investments_monte_carlo_simulations_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MonteCarloRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MonteCarloResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_monte_carlo_simulation_result_api_investments_monte_carlo_simulations__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MonteCarloResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
