BASE_MILESTONES = [
    {"hours": 1, "label": "Started", "short_label": "1h"},
    {"hours": 5, "label": "First Steps", "short_label": "5h"},
    {"hours": 10, "label": "Getting Warm", "short_label": "10h"},
    {"hours": 25, "label": "Committed", "short_label": "25h"},
    {"hours": 50, "label": "Initiate", "short_label": "50h"},
    {"hours": 75, "label": "Early Momentum", "short_label": "75h"},
    {"hours": 100, "label": "Apprentice I", "short_label": "100h"},
    {"hours": 150, "label": "Apprentice II", "short_label": "150h"},
    {"hours": 200, "label": "Apprentice III", "short_label": "200h"},
    {"hours": 300, "label": "Builder", "short_label": "300h"},
    {"hours": 400, "label": "Builder+", "short_label": "400h"},
    {"hours": 500, "label": "Practitioner", "short_label": "500h"},
    {"hours": 650, "label": "Serious Practitioner", "short_label": "650h"},
    {"hours": 800, "label": "Skilled I", "short_label": "800h"},
    {"hours": 1000, "label": "Skilled II", "short_label": "1k"},
    {"hours": 1250, "label": "Advanced I", "short_label": "1.25k"},
    {"hours": 1500, "label": "Advanced II", "short_label": "1.5k"},
    {"hours": 1750, "label": "Advanced III", "short_label": "1.75k"},
    {"hours": 2000, "label": "Craftsman", "short_label": "2k"},
    {"hours": 2500, "label": "Elite Beginner", "short_label": "2.5k"},
    {"hours": 3000, "label": "Professional I", "short_label": "3k"},
    {"hours": 3500, "label": "Professional II", "short_label": "3.5k"},
    {"hours": 4000, "label": "Professional III", "short_label": "4k"},
    {"hours": 4500, "label": "High Performer", "short_label": "4.5k"},
    {"hours": 5000, "label": "Expert I", "short_label": "5k"},
    {"hours": 5500, "label": "Expert II", "short_label": "5.5k"},
    {"hours": 6000, "label": "Expert III", "short_label": "6k"},
    {"hours": 6500, "label": "Specialist", "short_label": "6.5k"},
    {"hours": 7000, "label": "Authority", "short_label": "7k"},
    {"hours": 7500, "label": "Authority+", "short_label": "7.5k"},
    {"hours": 8000, "label": "Mastery Track", "short_label": "8k"},
    {"hours": 8500, "label": "Mastery Deepened", "short_label": "8.5k"},
    {"hours": 9000, "label": "Virtuoso", "short_label": "9k"},
    {"hours": 9500, "label": "Near Master", "short_label": "9.5k"},
]

DEFAULT_MAX_HOURS = 10000
